### ISSUE TITLE
Better Documentation Generator [$100]

### ISSUE THREAD

**Issue by lewisgoddard** [eustasy/vala-docs.org#1]
@eustasy/vala I think we should plan for this new generator because I think we have several people looking into it, but no actual roadmap.

---
- [x] Comments
- [x] Method Parameters / Arguments

---

Currently tracked at #4

**Comment by tintou** [comment]
`.gir` could be used, but there are also .metadata files used while generating .vapi files, and I'm unsure about the Vala native features or Posix features

**Comment by lewisgoddard** [comment]
What do the `.metadata` files look like? Where do they reside? What do they currently do?

**Comment by tintou** [comment]
some are here https://git.gnome.org/browse/vala/tree/vapi/metadata
some are inside projects sources

So it might be better to use `.vapi` files at the end :/

**Comment by lewisgoddard** [comment]
You guys are the experts, I know very little about that side of things. Whatever you all think is best.

**Comment by dahenson** [comment]
I could be wrong, but it seems like the .vapi files only hold half of the story. Part of what makes valadoc.org so useful is having all of those comments along with the structure of the library api. So, the generator would need to export both .vapi and associated comments.

**Comment by lewisgoddard** [comment]
I think the best immediate plan would be to strip down the existing generator to see where it sources its information and work from there, that way we are guaranteed to at least match its accuracy and depth.

**Comment by dahenson** [comment]
I agree. I'm trying to see what all valadoc does right now, and it seems like it wouldn't be too hard to modify it to spit out usable XML or JSON without a whole lot of effort.

**Comment by lewisgoddard** [comment]
The original is GPL v2, which I'm not a huge fan of, but I'm not adverse to having the generator be a separate license to the rest of the repository.

**Comment by MarcusWichelmann** [comment]
Using the `.gir` files directly doesn't make much sense imo, because `libvaladoc` puts all this information together anyway so we can generate one big json file per package easily. The advantage of json against xml is the smaller size (less traffic when sending them to the frontend) and in the end the json file might be more or less as big as the `.vapi` file.

**Comment by benwaffle** [comment]
We don't need to modify valadoc, we just need to write a doclet (which controls the output, such as html, gtk-doc, or in our case json)

**Comment by lewisgoddard** [comment]
So [gnome/valadoc](https://github.com/gnome/valadoc) is the raw valadoc, and we can just write a "doclet" for that to get JSON, completely circumventing the need to interact with [flobrosch/valadoc-org](https://github.com/flobrosch/valadoc-org)? That sounds like it should be far easier than interfering with that.

**Comment by btkostner** [comment]
I added a $50 bounty to this issue
https://www.bountysource.com/issues/29648191-better-documentation-generator

**Comment by lewisgoddard** [comment]
eustasy has doubled the bounty to $100: https://www.bountysource.com/issues/29648191-better-documentation-generator

**Comment by lewisgoddard** [comment]
So, #4 basically closes this I'm guessing?

**Comment by btkostner** [comment]
I think it does. Time to work on the web side.
